apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-site
  template:
    metadata:
      labels:
        app: nginx-site
    spec:
      containers:
      - name: nginx-site
        image: kiranmoluguri/kiran_1234:nginxserver
        imagePullPolicy: Always
        ports:
        - containerPort: 80
