apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: my-webapp
  name: my-webapp-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: my-webapp
    spec:
      containers:
      - image: kiranmoluguri/kiran_1234:mywebserver01
        name: my-webapp
        ports:
        - name: my-webapp
          containerPort: 8080      
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: my-webapp
  name: my-webapp
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: my-webapp
