apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: Myweb-app
  name: Myweb-app-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: Myweb-app
    spec:
      containers:
      - image: kiranmoluguri/kiran_1234:my-app-latest
        name: Myweb-app
        ports:
        - name: Myweb-app
          containerPort: 8080      
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: Myweb-app
  name: Myweb-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: Myweb-app
