apiVersion: v1
kind: pod
metadata:
  labels:
    name: mywebserver-app01
  spec:
   containers:
   - image: kiranmoluguri/kiran_1234:mywebserver01
      name: mywebserver
      ports:
    - name: mywebserver
      containerPort: 80
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mywebserver
  name: mywebserver
spec:
  type: nodeport
  ports:
    - port: 31200
      targetPort: 31200
  selector:
    name: mywebserver
