apiVersion: v1
kind: Deployment
metadata:
  labels:
    name: mywebapplication
  name: mywebapplication-ctl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        apps: mywebserver01
    spec:
      containers:
      - name: mywebserver01
        image: kiranmoluguri/kiran_1234:mywebserver01
        ports:
        - containerPort: 8081
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  name: mywebserver01
  namespace: development
spec:
  ports:
    - name: http
      port: 8081
  type: LoadBalancer    
  selector:
    apps: mywebserver01
