apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp-deployment
  labels:
    app: html
spec:
  replicas: 2
  selector:
    matchLabels:
      app: html
  template:
    metadata:
      labels:
        app: html
    spec:
      containers:
      - name: html
        image: kiranmoluguri/kiran_1234:mywebserver01
        ports:
        - containerPort: 80
---
# Loadbalancer Port Service
apiVersion: v1
kind: Service
metadata:
  name: mywebapp-deployment-service
spec:
  selector:
    app: html
  ports:
      port: 80
      targetPort: 31200
    type: LoadBalancer

