apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mywebserver02
  namespace: development
  labels:
    app: mywebserver02-app
spec:
  replicas: 4
  template:
    metadata:
      labels:
        apps: mywebserver02
    spec:
      containers:
      - name: mywebserver02
        image: kiranmoluguri/kiran_1234:mywebserver01
        ports:
        - containerPort: 8081
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  name: mywebserver02
  namespace: development
spec:
  ports:
    - name: http
      port: 8081
  type: LoadBalancer    
  selector:
    apps: mywebserver02
