apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mywebserver-app01
  name: mywebserver-controller01
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mywebserver
    spec:
      containers:
      - image: kiranmoluguri/kiran_1234:mywebserver01
        name: mywebserver
        ports:
        - name: mywebserver
          containerPort: 8080      
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mywebserver
  name: mywebserver
spec:
  type: ClusterIP
  ports:
    - port: 31000
      targetPort: 31000
  selector:
    name: mywebserver
