apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  labels:
    app: tomcat
spec:
  containers:
    - name: tomcat
      image: kiranmoluguri/kiran_1234:my-app-latest
      ports:
        - containerPort: 8080
