apiVersion: v1
kind: Service
metadata:
  name: Myweapp-service
  labels:
    app: Mywebapp-project
spec:
  selector:
    app: Mywebapp-project
  type: nodeport
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
