version: 2.1


jobs:
  self-hosted-agent-test:
    machine: true
    resource_class: onenessboy/devops-self-hosted-agent
    
    steps:
      - checkout
      - run: 
          name: access subscription
          command: az login --service-principal -u $spid -p $spkey --tenant $tenantid
      - run: 
          name: creating terraform remote backend resourcegroup
          command: az group create --location $region --name $terraformstoragerg
      - run: 
          name: creating storage account for terraform state
          command: az storage account create --name $terraformstorageaccount --resource-group $terraformstoragerg --location $region --sku Standard_LRS
      - run: 
          name: creating a container for tf state
          command: az storage container create --name terraform --account-name $terraformstorageaccount
      - run: 
          name: getting storage keys to validate tf file
          shell: powershell.exe
          command: $key=(Get-AzureRmStorageAccountKey -ResourceGroupName $terraformstoragerg -AccountName $terraformstorageaccount).Value[0]
      - run: 
          name: storing keys for further steps
          shell: powershell.exe
          command: Write-Host "##vso[task.setvariable variable=storagekey]$key"

workflows:
  my-workflow:
    jobs:
      - self-hosted-agent-test:
          context:
            - ab-synpase