version: 2.1


jobs:
  self-hosted-agent-test:
    machine: true
    resource_class: onenessboy/devops-self-hosted-agent
    
    steps:
      - checkout
      - run: az login --service-principal -u $spid -p $spkey --tenant $tenantid
      - run: az group create --location $region --name $terraformstoragerg
      - run: az storage account create --name $terraformstorageaccount --resource-group $terraformstoragerg --location $location --sku Standard_LRS
      - run: az storage container create --name terraform --account-name $terraformstorageaccount
      - run: $key=(Get-AzureRmStorageAccountKey -ResourceGroupName $terraformstoragerg -AccountName $terraformstorageaccount).Value[0];
      - run: Write-Host "##vso[task.setvariable variable=storagekey]$key"

workflows:
  my-workflow:
    jobs:
      - self-hosted-agent-test:
          context:
            - ab-synpase