version: 2.1


jobs:
  self-hosted-agent-test:
    machine: true
    resource_class: onenessboy/devops-self-hosted-agent
    
    steps:
      - checkout
      - run:
          name: "Terrform Remote Backend Setup"
          shell: powershell.exe
          command: |
            az login --service-principal -u $spid -p $spkey --tenant $tenantid
            az group create --location $region --name $terraformstoragerg
            az storage account create --name $terraformstorageaccount --resource-group $terraformstoragerg --location $location --sku Standard_LRS
            az storage container create --name terraform --account-name $terraformstorageaccount
            az storage account keys list -g $terraformstoragerg -n $terraformstorageaccount
            $key=(Get-AzureRmStorageAccountKey -ResourceGroupName $terraformstoragerg -AccountName $terraformstorageaccount).Value[0]
            Write-Host "##vso[task.setvariable variable=storagekey]$key";
  
workflows:
  my-workflow:
    jobs:
      - self-hosted-agent-test:
          context:
            - ab-synpase